import { customAlphabet } from 'nanoid';
import { DeviceRegistry } from './deviceRegistry.js';
import { issueAuthToken, verifyAuthToken } from './auth.js';
import { logger } from './logger.js';
import type { ErrorCode } from './messages.js';

const generateNumericCode = customAlphabet('0123456789', 6);
const CODE_TTL_MS = 5 * 60 * 1000; // 5 minutes

export interface PairingCodeEntry {
  code: string;
  hostDeviceId: string;
  expiresAt: number;
}

export interface PendingPairRequest {
  hostDeviceId: string;
  controllerDeviceId: string;
  controllerDeviceName: string;
  expiresAt: number;
}

export class PairingManager {
  private codes = new Map<string, PairingCodeEntry>();
  private hostToCode = new Map<string, string>();
  private pendingRequests = new Map<string, PendingPairRequest>(); // key: `${hostDeviceId}:${controllerDeviceId}`
  private cleanupInterval: NodeJS.Timeout | null = null;

  constructor(private registry: DeviceRegistry) {
    // Sweep expired codes periodically
    this.cleanupInterval = setInterval(() => this.cleanExpired(), 60 * 1000);
  }

  /**
   * Generates a 6-digit numeric pairing code for a host.
   */
  public createPairingCode(hostDeviceId: string): { code: string; expiresInSec: number } | { error: ErrorCode; message: string } {
    const host = this.registry.getByDeviceId(hostDeviceId);
    if (!host) {
      return { error: 'UNREGISTERED', message: 'Host is not registered' };
    }
    if (host.role !== 'host') {
      return { error: 'UNAUTHORIZED', message: 'Only hosts can create pairing codes' };
    }

    // Remove any previous code generated by this host
    const oldCode = this.hostToCode.get(hostDeviceId);
    if (oldCode) {
      this.codes.delete(oldCode);
      this.hostToCode.delete(hostDeviceId);
    }

    // Generate unique 6-digit code
    let code: string;
    let attempts = 0;
    do {
      code = generateNumericCode();
      attempts++;
    } while (this.codes.has(code) && attempts < 100);

    const expiresInSec = Math.floor(CODE_TTL_MS / 1000);
    const expiresAt = Date.now() + CODE_TTL_MS;

    const entry: PairingCodeEntry = {
      code,
      hostDeviceId,
      expiresAt,
    };

    this.codes.set(code, entry);
    this.hostToCode.set(hostDeviceId, code);

    logger.info({ hostDeviceId, code, expiresInSec }, 'Pairing code created');
    return { code, expiresInSec };
  }

  /**
   * Handles a controller attempting to pair using a code.
   */
  public handlePairRequest(
    controllerDeviceId: string,
    controllerDeviceName: string,
    code: string
  ): { success: boolean; errorCode?: ErrorCode; message?: string } {
    const controller = this.registry.getByDeviceId(controllerDeviceId);
    if (!controller) {
      return { success: false, errorCode: 'UNREGISTERED', message: 'Controller is not registered' };
    }
    if (controller.role !== 'controller') {
      return { success: false, errorCode: 'UNAUTHORIZED', message: 'Only controllers can initiate pair requests' };
    }

    const codeEntry = this.codes.get(code);
    if (!codeEntry) {
      return { success: false, errorCode: 'INVALID_CODE', message: 'Invalid pairing code' };
    }

    if (Date.now() > codeEntry.expiresAt) {
      this.codes.delete(code);
      this.hostToCode.delete(codeEntry.hostDeviceId);
      return { success: false, errorCode: 'CODE_EXPIRED', message: 'Pairing code has expired' };
    }

    const host = this.registry.getByDeviceId(codeEntry.hostDeviceId);
    if (!host) {
      return { success: false, errorCode: 'PEER_OFFLINE', message: 'Host is offline' };
    }

    // Store pending pair request
    const requestKey = `${host.deviceId}:${controllerDeviceId}`;
    this.pendingRequests.set(requestKey, {
      hostDeviceId: host.deviceId,
      controllerDeviceId,
      controllerDeviceName,
      expiresAt: codeEntry.expiresAt,
    });

    // Forward pair_request to host
    const sent = this.registry.sendTo(host.deviceId, {
      type: 'pair_request',
      fromDeviceId: controllerDeviceId,
      fromDeviceName: controllerDeviceName,
    });

    if (!sent) {
      this.pendingRequests.delete(requestKey);
      return { success: false, errorCode: 'PEER_OFFLINE', message: 'Host is unreachable' };
    }

    logger.info({ hostDeviceId: host.deviceId, controllerDeviceId }, 'Pair request forwarded to host');
    return { success: true };
  }

  /**
   * Handles a host approving a pair request.
   */
  public handleApprovePair(
    hostDeviceId: string,
    peerDeviceId: string
  ): { success: boolean; errorCode?: ErrorCode; message?: string } {
    const host = this.registry.getByDeviceId(hostDeviceId);
    if (!host) {
      return { success: false, errorCode: 'UNREGISTERED', message: 'Host is not registered' };
    }

    const controller = this.registry.getByDeviceId(peerDeviceId);
    if (!controller) {
      return { success: false, errorCode: 'PEER_OFFLINE', message: 'Controller is offline' };
    }

    const requestKey = `${hostDeviceId}:${peerDeviceId}`;
    this.pendingRequests.delete(requestKey);

    // Clean up pairing code associated with host
    const code = this.hostToCode.get(hostDeviceId);
    if (code) {
      this.codes.delete(code);
      this.hostToCode.delete(hostDeviceId);
    }

    // Issue JWT authToken
    const authToken = issueAuthToken(hostDeviceId, peerDeviceId);

    // Link active peers
    this.registry.linkPeers(hostDeviceId, peerDeviceId);

    // Send paired message to host
    this.registry.sendTo(hostDeviceId, {
      type: 'paired',
      peerDeviceId: controller.deviceId,
      peerDeviceName: controller.deviceName,
      authToken,
    });

    // Send paired message to controller
    this.registry.sendTo(peerDeviceId, {
      type: 'paired',
      peerDeviceId: host.deviceId,
      peerDeviceName: host.deviceName,
      authToken,
    });

    logger.info({ hostDeviceId, controllerDeviceId: peerDeviceId }, 'Pair approved and completed');
    return { success: true };
  }

  /**
   * Handles a host denying a pair request.
   */
  public handleDenyPair(
    hostDeviceId: string,
    peerDeviceId: string
  ): { success: boolean; errorCode?: ErrorCode; message?: string } {
    const requestKey = `${hostDeviceId}:${peerDeviceId}`;
    this.pendingRequests.delete(requestKey);

    const controller = this.registry.getByDeviceId(peerDeviceId);
    if (controller) {
      this.registry.sendTo(peerDeviceId, {
        type: 'pair_denied',
      });
    }

    logger.info({ hostDeviceId, controllerDeviceId: peerDeviceId }, 'Pair denied by host');
    return { success: true };
  }

  /**
   * Handles a controller resuming a previously paired session via JWT authToken.
   */
  public handleResumeSession(
    controllerDeviceId: string,
    peerDeviceId: string,
    authToken: string
  ): { success: boolean; errorCode?: ErrorCode; message?: string } {
    const controller = this.registry.getByDeviceId(controllerDeviceId);
    if (!controller) {
      return { success: false, errorCode: 'UNREGISTERED', message: 'Controller is not registered' };
    }

    const payload = verifyAuthToken(authToken);
    if (!payload) {
      return { success: false, errorCode: 'BAD_TOKEN', message: 'Invalid or expired auth token' };
    }

    // Verify token matches both devices (payload.hostDeviceId should be peerDeviceId, payload.controllerDeviceId should be controllerDeviceId)
    if (payload.hostDeviceId !== peerDeviceId || payload.controllerDeviceId !== controllerDeviceId) {
      return { success: false, errorCode: 'BAD_TOKEN', message: 'Auth token does not match peer devices' };
    }

    const host = this.registry.getByDeviceId(peerDeviceId);
    if (!host) {
      return { success: false, errorCode: 'PEER_OFFLINE', message: 'Host peer is offline' };
    }

    // Link peers
    this.registry.linkPeers(host.deviceId, controller.deviceId);

    // Send paired message to both sides
    this.registry.sendTo(controller.deviceId, {
      type: 'paired',
      peerDeviceId: host.deviceId,
      peerDeviceName: host.deviceName,
      authToken,
    });

    this.registry.sendTo(host.deviceId, {
      type: 'paired',
      peerDeviceId: controller.deviceId,
      peerDeviceName: controller.deviceName,
      authToken,
    });

    logger.info({ hostDeviceId: host.deviceId, controllerDeviceId: controller.deviceId }, 'Session resumed successfully');
    return { success: true };
  }

  /**
   * Cleans up any pairing state for a disconnected host or controller.
   */
  public handleDeviceDisconnect(deviceId: string): void {
    const code = this.hostToCode.get(deviceId);
    if (code) {
      this.codes.delete(code);
      this.hostToCode.delete(deviceId);
    }

    for (const [key, req] of this.pendingRequests.entries()) {
      if (req.hostDeviceId === deviceId || req.controllerDeviceId === deviceId) {
        this.pendingRequests.delete(key);
      }
    }
  }

  /**
   * Sweeps expired pairing codes and requests.
   */
  public cleanExpired(): void {
    const now = Date.now();
    for (const [code, entry] of this.codes.entries()) {
      if (now > entry.expiresAt) {
        this.codes.delete(code);
        this.hostToCode.delete(entry.hostDeviceId);
        logger.debug({ code, hostDeviceId: entry.hostDeviceId }, 'Pairing code expired and removed');
      }
    }

    for (const [key, req] of this.pendingRequests.entries()) {
      if (now > req.expiresAt) {
        this.pendingRequests.delete(key);
      }
    }
  }

  /**
   * Stops background interval (for cleanup/tests).
   */
  public destroy(): void {
    if (this.cleanupInterval) {
      clearInterval(this.cleanupInterval);
      this.cleanupInterval = null;
    }
  }
}
